program: train.py
method: grid
metric:
  name: val_major_rmse
  goal: minimize
parameters:
  pka_plm:
    values:
      [
        none,
        esm2_t48_15B_UR50D,
        esm2_t36_3B_UR50D,
        esm2_t33_650M_UR50D,
        esm2_t30_150M_UR50D,
        esm2_t12_35M_UR50D,
        esm2_t6_8M_UR50D,
        esm1b_t33_650M_UR50S,
        prot_t5_xl_half_uniref50-enc,
        prot_t5_xl_bfd,
      ]
  pka_dim:
    values: [64, 128, 256, 512]
  pka_layers:
    values: [1, 2, 3, 4]
  kfold:
    values: [5]
